

utils::globalVariables(c('site', 'person_id', 'patid', 'start_date',
                         'end_date', 'care_site_id', 'provider_id', 'encounterid',
                         'visit_occurrence_id', 'visit_detail_id', 'visit_concept_id',
                         'visit_detail_concept_id', 'visit_start_date', 'enc_type',
                         'visit_detail_start_date', 'vocabulary_id', 'specialty_concept_id',
                         'specialty_concept_id_pv', 'specialty_concept_id_cs', 'facility_type',
                         'admit_date', 'age_grp', 'anomaly_yn', 'birth_date',
                         'category', 'cl', 'cluster', 'codeset_name', 'concept_code',
                         'concept_id', 'concept_name', 'dist_eucl_mean', 'dist_mean',
                         'dist_mean_sum', 'facet_col', 'group', 'lcl', 'mad_val',
                         'mean_val', 'median_val', 'sd_val', 'max_age', 'min_age',
                         'mean_allsiteprop', 'mean_site_loess', 'n_grp', 'num_visits',
                         'overall_sd', 'prop', 'provider_specialty_primary', 'providerid',
                         'site_loess', 'specialty_name', 'sumn', 'text_raw', 'text_smooth',
                         'time_end', 'time_start', 'time_increment', 'tooltip',
                         'top_n_indicator', 'total', 'ucl', 'x', 'y', 'zscr', 'closest_site',
                         'delim', 'farthest_site', 'iqr_val', 'med', 'q1', 'q3', 'nvar',
                         'site_anoms', 'site_w_anom', 'value'))
